### ISSUE TITLE
Dr CAO Head Ambassador Oct. 2024

### ISSUE THREAD

**Issue by ahjxcrz** [neurolanche/Neurolanche-Ambassador-Program#104]
Personal info:
Amb rank: Head Ambassador
Telegram Username: ahjxcrz
Twitter URL: [twitter.com/cao_lab
Astar Wallet Address: 5G9xRrcQZY6yaKYr3o3etJt2hJMp1smhJEk74bgmT7e97f6j

AM to Chinese translation:
Organized and had several Chinese articles in my community Polkaverse， shared Astar eco, Neurolanche, like:
https://grillapp.net/@aiweb3/astar-network-web3-219270
https://grillapp.net/@aiweb3/a-iweb3-2024-10-21-1-217234
https://grillapp.net/@aiweb3/astar-lfgm-soneium-spark-216433
https://grillapp.net/@aiweb3/a-iweb3-2024-10-14-1-215433
https://grillapp.net/@aiweb3/astar-lfgm-ai-web3-215032
https://grillapp.net/@aiweb3/next-x-startale-x-astar-network-web3-214364
https://grillapp.net/@aiweb3/ai-web3-neemo-nft-211765

https://x.com/cao_lab/status/1851688220268073200
https://x.com/cao_lab/status/1851301353567764761
https://x.com/cao_lab/status/1850013214500847747
https://x.com/cao_lab/status/1849127013736694169
https://x.com/cao_lab/status/1848426563462902083
https://x.com/cao_lab/status/1847635871379705880
https://x.com/cao_lab/status/1847150451378250169
https://x.com/cao_lab/status/1846963249939730764
https://x.com/cao_lab/status/1846759658855584063
https://x.com/cao_lab/status/1846033270326403511
https://x.com/cao_lab/status/1846032939563589880
https://x.com/cao_lab/status/1844786953834918068
https://x.com/cao_lab/status/1844759943632818416
https://x.com/cao_lab/status/1844759567416303801
https://x.com/cao_lab/status/1844034090062037331
https://x.com/cao_lab/status/1843712505237123538
https://x.com/cao_lab/status/1843710814160900138
https://x.com/cao_lab/status/1843515491295605044
https://x.com/cao_lab/status/1843515052911190389
https://x.com/cao_lab/status/1842627798265209189
https://x.com/cao_lab/status/1842592333931614231
https://x.com/cao_lab/status/1842566911508508827
https://x.com/cao_lab/status/1842266114853904554
https://x.com/cao_lab/status/1841161865763963388
https://x.com/cao_lab/status/1841157934312800551
https://x.com/aiweb3dao/status/1846964952630022355

Videos:
https://www.youtube.com/watch?v=JwJAOLVAjeU
https://www.youtube.com/watch?v=pai3sD1aLaU
https://www.youtube.com/watch?v=zCNqvqJXuyU
https://www.youtube.com/watch?v=x3GIbuP6ghM
https://www.youtube.com/watch?v=nAOy6gohZKo
https://www.youtube.com/watch?v=HFalDCTRetg

WM:
participated in all weekly meeting

CM to community:
Yes, in the AIWeb3 chinese community, wechat and Astar wechat/tg channel, posting Neurolanche, answer questions about dApp staking.

Business Dev and events:

Organize and translate the twitter space specialized Astar voting period with three top dApp from Astar network:Neurolanche, Neemo Finance and DeStore: https://x.com/aiweb3dao/status/1847284331728994336 , 46.4k tuned in.

The discord dragon card game with Neurolanche dragon card. Right now, users can use the point to buy the Neurolanche card and also burn the card to get Astar tokens, already sent few hundreds Astar tokens to the community and request the community to stake it on Neurolanche dApp.
In addition, we are waiting for the clan system, and hope to organize bigger event with Neurolanche.
In AIWeb3, we will also organize the Zealy event, and would be happy to work with Neurolanche on it!
I have also reached out community members and stake astar on Neurolanche!

**Comment by neurolanche** [comment]
Hi, could you also add your Astar EVM wallet address?
