### ISSUE TITLE
October 2024 Activity Report Suisei

### ISSUE THREAD

**Issue by suisei-cmd** [neurolanche/Neurolanche-Ambassador-Program#107]
personal information: Rank: Ambassador
Telegram Username：@Suisei_Ne
UNCHER X(twitter): @Suisei_nft 
Discord username: suisei_rx7
ASTAR native wallet address：WDzujrtnMgzuaZSLiZfuVvragxoHMauLYopEq3pij5uDX93

Tasks;
Content Creator(All posts on X (Twitter) and my QTs:

AM:
https://x.com/Suisei_nft/status/1841748681982345367
https://x.com/Suisei_nft/status/1841477269593936299
https://x.com/Suisei_nft/status/1840726927898001780
https://x.com/Suisei_nft/status/1842923815124472019
https://x.com/Suisei_nft/status/1842919878212432348
https://x.com/Suisei_nft/status/1842199527316767167
https://x.com/Suisei_nft/status/1842195826422305090
https://x.com/Suisei_nft/status/1841748681982345367
https://x.com/Suisei_nft/status/1843998002211627460
https://x.com/Suisei_nft/status/1843639009299533984
https://x.com/Suisei_nft/status/1844736617388593599
https://x.com/Suisei_nft/status/1845364566919872620
https://x.com/Suisei_nft/status/1845445245896720522
https://x.com/Suisei_nft/status/1846907288935858470
https://x.com/Suisei_nft/status/1847547815041622021
https://x.com/Suisei_nft/status/1848033671850401937
https://x.com/Suisei_nft/status/1849372977537986656
https://x.com/Suisei_nft/status/1851241059608904053
https://x.com/Suisei_nft/status/1851976957996732845

CM:
Task; Content Creator (X (Twitter) and all my QT posts:In addition, the following activities were carried out:⬇️
①Neurolanche Staking Support
②Michael’s Discord support
③Neurolanche Discord、Japanese room support
④Japanese-language adaptation of materials
⑤ZKSTRIKE is held daily.

CC:
　✅ Translated tweets and translated documents above.
EM:
　✅ He communicates with local community members on Michael's Discord. Invitation to Enter Neuro

**Comment by neurolanche** [comment]
Hi, could you also add your Astar EVM wallet address? It will be required to claim the NEROX ambassador rewards.

**Comment by suisei-cmd** [comment]
Here is my EVM address.

0xa1667793df596232741f771C180F10b37534ec14
