### ISSUE TITLE
October 2024 Contribution - ludens_jp1977

### ISSUE THREAD

**Issue by ludens-jp** [neurolanche/Neurolanche-Ambassador-Program#109]
personal information: 
Rank: Ambassador
Telegram Username：ludens_jp
Twitter URL:https://twitter.com/minstrel1977
Discord username: ludens.jp1977
ASTAR native wallet address：anqg7cyTqrz6FvF81NEKKgMzcuQgQdKqHJqJkyKigpNr8ZJ
EVM address: 0xa91A73C911935e93A977B9FDE9F29DAB81fb6BC8

Taks:
· AM:
https://x.com/minstrel1977/status/1841592983520739749?s=46&t=m59637vjtaF1PnWruzkhgw
https://x.com/minstrel1977/status/1842194748423180610?s=46&t=m59637vjtaF1PnWru
https://x.com/minstrel1977/status/1843411370118914425?s=46&t=m59637vjtaF1PnWruzk
https://x.com/minstrel1977/status/1843634801406030099?s=46&t=m59637vjtaF1PnWruz
https://x.com/minstrel1977/status/1843982860136714598?s=46&t=m59637vjtaF1PnWruzkhgw
https://x.com/minstrel1977/status/1844720102366949770?s=46&t=m59637vjtaF1PnWruzkhgw
https://x.com/minstrel1977/status/1845822501924089908?s=46&t=m59637vjtaF1PnWruz
https://x.com/minstrel1977/status/1846886789421977872?s=46&t=m59637vjtaF1PnWruzkh
https://x.com/minstrel1977/status/1847547585160237295?s=46&t=m59637vjt
https://x.com/minstrel1977/status/1847612485412803033?s=46&t=m59637vjtaF1PnWruzkhgw
https://x.com/minstrel1977/status/1848348354872537283?s=46&t=m59637vjtaF1PnWruzkh
https://x.com/minstrel1977/status/1849091881839579464?s=46&t=m59637vjtaF1PnWruzkh
https://x.com/minstrel1977/status/1849799800046452947?s=46&t=m59637vjtaF1PnWruzkhgw
https://x.com/minstrel1977/status/1851249753809698962?s=46&t=m59637vjtaF1PnWruzk
https://x.com/minstrel1977/status/1851364812909154557?s=46&t=m59637vjtaF1PnWruzkhgw
https://x.com/minstrel1977/status/1851976295682576680?s=46&t=m59637vjtaF1PnWruzkh

· CM:
In October, we optimized efficiency by holding events on weekday mornings, and announced Zk Strike game times on Discord to create an environment where anyone could play. In November, we will continue to use Zk Strike while changing the game mode and expanding the gateway to Neurolanche.

![image](https://github.com/user-attachments/assets/a5cfa8d4-a1fd-4dd6-b979-dba3d4613b3b)
![image](https://github.com/user-attachments/assets/08623276-9904-4a3b-ae8d-ce92b39c90fe)

**Comment by neurolanche** [comment]
Hi, could you also add your Astar EVM wallet address? It will be required to claim the NEROX ambassador rewards.

**Comment by neurolanche** [comment]
Hi, could you also add your Astar EVM wallet address? It will be required to claim the NEROX ambassador rewards.

**Comment by ludens-jp** [comment]
Ok!I will add it later.
Thanks.

**Comment by ludens-jp** [comment]
EVM address added.
Please confirm.
