### ISSUE TITLE
October 2024 Contribution - Favour 

### ISSUE THREAD

**Issue by BBoss01** [neurolanche/Neurolanche-Ambassador-Program#111]
Amb Rank : Ambassador
Telegram username : @Fhavourites 
Discord username: favour_cy
Twitter Link : https://twitter.com/official_bles1?t=eR-KQW9NjmPi7pCNo7ziLg&s=09

Astar native wallet address : ZNsv34wKt7qNXz5ZwjEiWpu3cu4vVunf8Cc2SJM9EH9bx7z

Astar Evm wallet address: 0x6CB254F45186a2B195531b35b83F61A31611dD69

TASKS

SM 

I promoted Neurolanche on X by creating informative threads, quote posting and sharing posts from the global X account and team members. I also created some LinkedIn Posts and Warpcast Posts.

X Posts

https://x.com/official_bles1/status/1852413685148393880?t=nS2ByjhLlFQDKHF5wAqRDQ&s=19

https://x.com/official_bles1/status/1851910602551111898?t=GXo3PLyNV7d1sq9d3k87bw&s=19

https://x.com/official_bles1/status/1849409361933738062?t=rmFM1Y4lBmxqS_vXTZWlKQ&s=19

https://x.com/official_bles1/status/1847185771251261622?t=eMCBqKR_odnb5owF_Jp9dw&s=19

https://x.com/official_bles1/status/1844295921565311453?t=FpcwnoQn3NSc7ijrOv8tUA&s=19

https://x.com/official_bles1/status/1853121316225765538?t=Znh78K_qROLMD2_JbrqqMQ&s=19

https://x.com/official_bles1/status/1851316263714504958?t=T6I37ULhn3bwAKvrHVoAAA&s=19

https://x.com/official_bles1/status/1849847623999684860?t=lZ8te7Fv1NukmisIKAt1eA&s=19

https://x.com/official_bles1/status/1849147965778112887?t=-vP5Dq3SergCUGLYL7k45Q&s=19

https://x.com/official_bles1/status/1848353379476492494?t=DZv21aU8u8aqz04_nWJ_UQ&s=19

https://x.com/official_bles1/status/1847560504358604875?t=nRLuuyAXn-dcfLuilxIqdQ&s=19

https://x.com/official_bles1/status/1846888436222824713?t=1HPR95Qzw4j22zvrFQ8Ehg&s=19

https://x.com/official_bles1/status/1845879106980008361?t=eXEL-PhXKFMSOrs5Va09KA&s=19

https://x.com/official_bles1/status/1845474255779090929?t=bdngi2WBc5kVz1uBbREnFw&s=19

https://x.com/official_bles1/status/1844715592470634509?t=vDXPFGlIre0Sqs3pF7NEag&s=19

https://x.com/official_bles1/status/1843647113768653133?t=ttLNWgXTqnTdKM0GIm3VqA&s=19

https://x.com/official_bles1/status/1843366543843049706?t=FxqtVJaShQ6K7awo6cRMTg&s=19

LinkedIn Posts 

https://www.linkedin.com/posts/favour-solomon-99b430236_ton-web3gaming-nerodog-activity-7258155125574172673-bMoB

https://www.linkedin.com/posts/favour-solomon-99b430236_ai-web3-blockchain-activity-7258154534953230336-bh0j

https://www.linkedin.com/posts/favour-solomon-99b430236_ai-web3-blockchain-activity-7255508333246185472-ZvRC

https://www.linkedin.com/posts/favour-solomon-99b430236_ai-web3-blockchain-activity-7255501341618229248-wtlB

Warpcast Posts 

https://warpcast.com/favour01/0xc5f95939

https://warpcast.com/favour01/0x0993d769

https://warpcast.com/favour01/0xaa17c544

https://warpcast.com/favour01/0x43e6276b

CM 

I had some engagement in Neurolanche discord and telegram community.

WM

I attended all community events.

SUPPLEMENTARY TASKS 

CC

I created two articles about neurolanche

- Nero Dog: A new chapter in the world of Tap-to-Earn Applications: This article explores the latest developments about Nero Dog 

https://medium.com/@boyesolomon8/nero-dog-a-new-chapter-in-the-world-of-tap-to-earn-applications-27b6f48b0312

- Neurolanche Pioneering a new era of technological innovation: This article explores the vision, philosophy, and potential benefits of Neurolanche’s endeavors, making their mission comprehensible and exciting for everyone.

https://medium.com/@boyesolomon8/neurolanche-pioneering-a-new-era-of-technological-innovation-2f198bda8c8d

ART

I created some graphic contents about Neurolanche

![1000982673.png](https://github.com/user-attachments/assets/84c1d661-7b2d-4d78-966c-daad91a72af5)

![Blue Gradient Company Business Profile Presentation_20241025_101738_0000.png](https://github.com/user-attachments/assets/922e28ea-164b-4ba8-a2eb-82bf932d601b)

![Blue Gradient Company Business Profile Presentation_20241101_172847_0000.png](https://github.com/user-attachments/assets/8a68fb65-d533-4bb8-872a-61c206c5e002)

![1_ORMvcniBQMGGzQk9r4qyYg~2.jpg](https://github.com/user-attachments/assets/a92f06f5-e03d-4f43-9854-f52e822366e9)

![1_PBCgYlDs0q0kNPA2Qfzg2A~2.jpg](https://github.com/user-attachments/assets/f43f0d81-712e-4512-87c6-63c124a37551)

**Comment by neurolanche** [comment]
Hi, could you also add your Astar EVM wallet address? It will be required to claim the NEROX ambassador rewards.

**Comment by BBoss01** [comment]
Updated, Thank you.
