### ISSUE TITLE
October contributions - HA Emil Kietzman 2024

### ISSUE THREAD

**Issue by EmilKietzman** [neurolanche/Neurolanche-Ambassador-Program#112]
Title: October 2024 Contribution - {EmilKietzman}

Personal info:
Amb rank: Head Ambassador
Telegram Username: EmilKietzman
Twitter URL: [twitter.com/EmilKietzman]
Astar Native Address: YyqHzWJMyLHqb3Vpy955gURhQaWXqY48r5GH3Tw9QW5QN1z
Astar EVM: 0x91797B965279cAE6fE8F219033434Fc1482F55a2
Tasks:

AM:
Focusing on Nero DOG, talking on priv with multiple people on errors, referals, gameplay & other questions. Asking questions on Soneium. Managing the polish community, educating on Neurolanche

QRT:

https://x.com/EmilKietzman/status/1841479876890525867
https://x.com/EmilKietzman/status/1842899332598542487
https://x.com/EmilKietzman/status/1843634857756504255
https://x.com/EmilKietzman/status/1844719265330397391
https://x.com/EmilKietzman/status/1846890062740361404
https://x.com/EmilKietzman/status/1847611762163494917
https://x.com/EmilKietzman/status/1848392150100168981
https://x.com/EmilKietzman/status/1849088530946961559
https://x.com/EmilKietzman/status/1849785700343755092
https://x.com/EmilKietzman/status/1851234930577092932

RT:

https://x.com/neurolanche/status/1842185525341663614
https://x.com/neurolauncher/status/1842525377002094896
https://x.com/neurolauncher/status/1843294012662526277
https://x.com/neurolanche/status/1843977563565432964
https://x.com/neurolanche/status/1845435730841243901
https://x.com/neurolanche/status/1845810521716777290
https://x.com/neurolauncher/status/1846952456846299448
https://x.com/neurolauncher/status/1847546376466632913
https://x.com/neurolauncher/status/1851652730022212032
https://x.com/neurolanche/status/1851973615333577214

Focused mostly on Telegram & X activity, answered tons of DMs on Nero Dog, roadmap of Nerox AI and the Soneium plus activities before TGE in November

Twitter followers in October 2950

Community Management:
In October very active on Neurolanche Telegram
Replying to People on discord/X with questions on Neurolanche
Managing Polish Community on Discord Channel on Astar & Neurolanche

Giving advise to People how to stake on Neurolanche on Dapp staking season III soon coming & use Nero Dog

Did a lot of moderating on the TG channel

Attended all Neurolanche Ambassador Meetings & AMA's & joined the X spaces

**Comment by neurolanche** [comment]
Hi, could you also add your Astar EVM wallet address? It will be required to claim the NEROX ambassador rewards.

**Comment by EmilKietzman** [comment]
done :)
