### ISSUE TITLE
April and before 2024 Contributions - Giki

### ISSUE THREAD

**Issue by GikiRun** [neurolanche/Neurolanche-Ambassador-Program#50]
Tweet：
https://x.com/GikiRun/status/1783773871767945487
https://x.com/GikiRun/status/1784928333589094889
https://x.com/GikiRun/status/1762152902997737676
https://x.com/GikiRun/status/1745637641192919250
https://x.com/GikiRun/status/1745994192143393139

Video：
https://www.youtube.com/watch?v=UZySN9jSRqA
https://www.youtube.com/watch?v=4wvQxW8lTCs

Organized and Hosted the Twitter Space：
https://x.com/aiweb3dao/status/1745113727060586899

Offline Meetup in China and introduced the projects of Polkadot ecosystem
Introduced Neurolanche at 11'13''
https://youtu.be/ou_yPrXF2mA?si=SN6_aMZdT1xoHda8&t=676

**Comment by neurolanche** [comment]
To be eligible for the reward, please share your Astar native address.
