### ISSUE TITLE
May 2024 Contributions - Giki

### ISSUE THREAD

**Issue by GikiRun** [neurolanche/Neurolanche-Ambassador-Program#51]
Tweet:
https://x.com/GikiRun/status/1793635801445921149
https://x.com/GikiRun/status/1794003252448817206
https://x.com/GikiRun/status/1795021891167453310
https://x.com/GikiRun/status/1796549494697578765
https://x.com/GikiRun/status/1798347081486373187
https://x.com/GikiRun/status/1798355378302079340

Organized and Hosted the Twitter Space:
https://x.com/aiweb3dao/status/1791396012051083270

**Comment by neurolanche** [comment]
To be eligible for the reward, please share your Astar native address.
